### ISSUE TITLE
Unit stayed in awaiting  for member to start

### ISSUE THREAD

**Issue by mathmarchand** [canonical/postgresql-operator#775]
## Steps to reproduce

1. Deploy charmed postgresql VM with 3 nodes.
2. Add data to the primary node when available. 
3. Wait
4. Most of the time one node will stay stuck at awaiting.

## Expected behavior
All nodes bootstrap to the cluster correctly

## Actual behavior
One node stay waiting. It is starting to bootstrap on the primary node, but juju check if the process is running after 1 minutes and restart the process, restarting the bootstrap. Eventually it passed if it managed to bootstrap inside 1 minutes.

![Image](https://github.com/user-attachments/assets/526a57e3-7713-45d4-9733-0235a6662125)

## Versions

Operating system: Ubuntu 22.04.05 LTS

Juju CLI:  3.6.2

Juju agent: 3.6.2

Charm revision:  468

LXD: 5.0.4 

## Log output

Juju debug log:  See in the the screenshot above

## Additional context

It is the postgresql DB for landscape deployment on VMs.

**Comment by mathmarchand** [comment]
![Image](https://github.com/user-attachments/assets/03ab7477-f9fd-4488-8dfa-246fce7bb962)

some more logs from /var/log/syslog, systemd tries to stop patroni, then there a apparmor error then the the process get kill.

**Comment by mathmarchand** [comment]
Also, changing the model config for update-status-hook-interface to 10m temporarily to get the unit to bootstrap seems to work. Not sure if it was the reason, but the unit finally started.

![Image](https://github.com/user-attachments/assets/d465aa2e-33fc-422d-af5e-00ab50c71eb4)

**Comment by dragomirp** [comment]
Hi, @mathmarchand, there are fixes for Juju 3.6 in the latest `14/stable` release (revs. 552, 553). Can you try if your issue persists using that revisions?

**Comment by mathmarchand** [comment]
Hi @dragomirp,

Thank you for your patience! I was finally able to redeploy landscape to test newer revision (553) of the charm and after 3 tests, I was no longer seeing the issue. I will close the issue, since it is already resolved.

Regards,
Mathieu

**Comment by hloeung** [comment]
Would this also fix existing environments seeing this issue with the charms upgraded to 553? Or only for new deployments?

Asking because we're still seeing environments with units stuck in "awaiting for member to start".

**Comment by dragomirp** [comment]
> Would this also fix existing environments seeing this issue with the charms upgraded to 553? Or only for new deployments?
> 
> Asking because we're still seeing environments with units stuck in "awaiting for member to start".

Unless those environments are running on Juju 3.6, this should be unrelated.
